import { LitElement, PropertyValues, TemplateResult } from 'lit-element';
import '@material/mwc-list/mwc-check-list-item';
import '@material/mwc-list/mwc-radio-list-item';
import '@material/mwc-button';
import '@material/mwc-icon-button';
import '@compas-oscd/open-scd/dist/oscd-filter-button.js';
import './ied/element-path.js';
import './ied/create-ied-dialog.js';
import './ied/add-access-point-dialog.js';
import './ied/add-ldevice-dialog.js';
import './ied/add-ln-dialog.js';
import { Nsdoc } from '@compas-oscd/open-scd/dist/foundation/nsdoc.js';
import { OscdApi } from '@compas-oscd/core';
import { CreateIedDialog } from './ied/create-ied-dialog.js';
import { AddAccessPointDialog } from './ied/add-access-point-dialog.js';
import { AddLDeviceDialog } from './ied/add-ldevice-dialog.js';
import { AddLnDialog } from './ied/add-ln-dialog.js';
/** An editor [[`plugin`]] for editing the `IED` section. */
export default class IedPlugin extends LitElement {
    /** The document being edited as provided to plugins by [[`OpenSCD`]]. */
    doc: XMLDocument;
    editCount: number;
    /** All the nsdoc files that are being uploaded via the settings. */
    nsdoc: Nsdoc;
    oscdApi: OscdApi | null;
    createIedDialog: CreateIedDialog;
    treeAddAccessPointDialog: AddAccessPointDialog;
    treeAddLDeviceDialog: AddLDeviceDialog;
    treeAddLnDialog: AddLnDialog;
    selectedIEDs: string[];
    selectedLNClasses: string[];
    private selectedHierarchyNode?;
    private expandedTreeNodes;
    private expandedTableNodes;
    private treeActionNode?;
    private treeWidth?;
    private get iedList();
    private get lnClassList();
    private get selectedIed();
    connectedCallback(): void;
    disconnectedCallback(): void;
    private createVirtualIED;
    protected updated(_changedProperties: PropertyValues): void;
    private loadPluginState;
    private storePluginState;
    private onSelectionChange;
    private isVisible;
    private getChildren;
    private hasChildren;
    private resetHierarchy;
    private selectHierarchyNode;
    private nodeLabel;
    private toggleNode;
    private openTreeDialog;
    private createAccessPoint;
    private createLDevice;
    private createLN;
    private removeElement;
    private runTreeAction;
    private renderTreeActions;
    private renderTreeNode;
    private tableRows;
    private resizeTree;
    private renderTableElement;
    private renderHierarchy;
    private renderIEDList;
    render(): TemplateResult;
    static styles: import("lit-element").CSSResult;
}
